//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DocumentumArchivageSettings {
    
    private DocumentumArchivageSettingsSetting[] itemsField;
    
    private System.DateTime creationDateField;
    
    private System.DateTime updateDateField;
    
    private bool updateDateFieldSpecified;
    
    private string authorEmailField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Setting", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DocumentumArchivageSettingsSetting[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime creationDate {
        get {
            return this.creationDateField;
        }
        set {
            this.creationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime updateDate {
        get {
            return this.updateDateField;
        }
        set {
            this.updateDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool updateDateSpecified {
        get {
            return this.updateDateFieldSpecified;
        }
        set {
            this.updateDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string authorEmail {
        get {
            return this.authorEmailField;
        }
        set {
            this.authorEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DocumentumArchivageSettingsSetting {
    
    private string documentTypeField;
    
    private DocumentumArchivageSettingsSettingFileConditions fileConditionsField;
    
    private IfNotExistsComplexType cabinetField;
    
    private IfNotExistsComplexType folderPathField;
    
    private DocumentumArchivageSettingsSettingProperty[] propertiesField;
    
    private string nameField;
    
    private bool enabledField;
    
    public DocumentumArchivageSettingsSetting() {
        this.enabledField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DocumentType {
        get {
            return this.documentTypeField;
        }
        set {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DocumentumArchivageSettingsSettingFileConditions FileConditions {
        get {
            return this.fileConditionsField;
        }
        set {
            this.fileConditionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IfNotExistsComplexType Cabinet {
        get {
            return this.cabinetField;
        }
        set {
            this.cabinetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IfNotExistsComplexType FolderPath {
        get {
            return this.folderPathField;
        }
        set {
            this.folderPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DocumentumArchivageSettingsSettingProperty[] Properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DocumentumArchivageSettingsSettingFileConditions {
    
    private DocumentumArchivageSettingsSettingFileConditionsName nameField;
    
    private DocumentumArchivageSettingsSettingFileConditionsExtension[] extensionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DocumentumArchivageSettingsSettingFileConditionsName Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Extension", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DocumentumArchivageSettingsSettingFileConditionsExtension[] Extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DocumentumArchivageSettingsSettingFileConditionsName {
    
    private string regexpField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string regexp {
        get {
            return this.regexpField;
        }
        set {
            this.regexpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class IfNotExistsComplexType {
    
    private IfNotExistsSimpleType ifNotExistsField;
    
    private string valueField;
    
    public IfNotExistsComplexType() {
        this.ifNotExistsField = IfNotExistsSimpleType.ThrowError;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(IfNotExistsSimpleType.ThrowError)]
    public IfNotExistsSimpleType ifNotExists {
        get {
            return this.ifNotExistsField;
        }
        set {
            this.ifNotExistsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
public enum IfNotExistsSimpleType {
    
    /// <remarks/>
    ThrowError,
    
    /// <remarks/>
    Skip,
    
    /// <remarks/>
    Create,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DocumentumArchivageSettingsSettingFileConditionsExtension {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DocumentumArchivageSettingsSettingProperty {
    
    private DocumentumArchivageSettingsSettingPropertySources[] sourcesField;
    
    private string nameField;
    
    private string defaultValueField;
    
    private DocumentumArchivageSettingsSettingPropertyType typeField;
    
    private bool enabledField;
    
    private DocumentumArchivageSettingsSettingPropertyIfNotFound ifNotFoundField;
    
    public DocumentumArchivageSettingsSettingProperty() {
        this.typeField = DocumentumArchivageSettingsSettingPropertyType.String;
        this.enabledField = true;
        this.ifNotFoundField = DocumentumArchivageSettingsSettingPropertyIfNotFound.DefaultValue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Sources", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DocumentumArchivageSettingsSettingPropertySources[] Sources {
        get {
            return this.sourcesField;
        }
        set {
            this.sourcesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultValue {
        get {
            return this.defaultValueField;
        }
        set {
            this.defaultValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(DocumentumArchivageSettingsSettingPropertyType.String)]
    public DocumentumArchivageSettingsSettingPropertyType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(DocumentumArchivageSettingsSettingPropertyIfNotFound.DefaultValue)]
    public DocumentumArchivageSettingsSettingPropertyIfNotFound ifNotFound {
        get {
            return this.ifNotFoundField;
        }
        set {
            this.ifNotFoundField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DocumentumArchivageSettingsSettingPropertySources {
    
    private DocumentumArchivageSettingsSettingPropertySourcesSourcePDFBookmark sourcePDFBookmarkField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DocumentumArchivageSettingsSettingPropertySourcesSourcePDFBookmark SourcePDFBookmark {
        get {
            return this.sourcePDFBookmarkField;
        }
        set {
            this.sourcePDFBookmarkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DocumentumArchivageSettingsSettingPropertySourcesSourcePDFBookmark {
    
    private bool isRequiredField;
    
    private string separatorField;
    
    private string indexLineField;
    
    private string indexPositionField;
    
    public DocumentumArchivageSettingsSettingPropertySourcesSourcePDFBookmark() {
        this.isRequiredField = true;
        this.separatorField = "";
        this.indexPositionField = "0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool isRequired {
        get {
            return this.isRequiredField;
        }
        set {
            this.isRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string separator {
        get {
            return this.separatorField;
        }
        set {
            this.separatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string indexLine {
        get {
            return this.indexLineField;
        }
        set {
            this.indexLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string indexPosition {
        get {
            return this.indexPositionField;
        }
        set {
            this.indexPositionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DocumentumArchivageSettingsSettingPropertyType {
    
    /// <remarks/>
    String,
    
    /// <remarks/>
    Decimal,
    
    /// <remarks/>
    DateTime,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DocumentumArchivageSettingsSettingPropertyIfNotFound {
    
    /// <remarks/>
    DefaultValue,
    
    /// <remarks/>
    ThrowError,
    
    /// <remarks/>
    Skip,
}
