//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XsdFormEditor.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XsdFormEditor.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  *.
        /// </summary>
        internal static string ControlFactory_GetGroupBoxFromContainer___ {
            get {
                return ResourceManager.GetString("ControlFactory_GetGroupBoxFromContainer___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  *.
        /// </summary>
        internal static string ControlManager_GetGroupBoxFromContainer___ {
            get {
                return ResourceManager.GetString("ControlManager_GetGroupBoxFromContainer___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during loading XML file with form data..
        /// </summary>
        internal static string MainForm_LoadXmlToolStripMenuItemClick_Error_during_loading_XML_file_with_form_data_ {
            get {
                return ResourceManager.GetString("MainForm_LoadXmlToolStripMenuItemClick_Error_during_loading_XML_file_with_form_da" +
                        "ta_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (*.xml)|*.xml|All Files (*.*)|*.*.
        /// </summary>
        internal static string MainForm_LoadXmlToolStripMenuItemClick_XML_Files____xml____xml_All_Files__________ {
            get {
                return ResourceManager.GetString("MainForm_LoadXmlToolStripMenuItemClick_XML_Files____xml____xml_All_Files_________" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during processing XSD schema:.
        /// </summary>
        internal static string MainForm_LoadXSDToolStripMenuItemClick_Error_during_processing_XSD_schema_ {
            get {
                return ResourceManager.GetString("MainForm_LoadXSDToolStripMenuItemClick_Error_during_processing_XSD_schema_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSD Files (*.xsd)|*.xsd|All Files (*.*)|*.*.
        /// </summary>
        internal static string MainForm_LoadXSDToolStripMenuItemClick_XSD_Files____xsd____xsd_All_Files__________ {
            get {
                return ResourceManager.GetString("MainForm_LoadXSDToolStripMenuItemClick_XSD_Files____xsd____xsd_All_Files_________" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MainForm_SaveXmlAsToolStripMenuItemClick_Error {
            get {
                return ResourceManager.GetString("MainForm_SaveXmlAsToolStripMenuItemClick_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during saving XML file with data to the file..
        /// </summary>
        internal static string MainForm_SaveXmlAsToolStripMenuItemClick_Error_during_saving_XML_file_with_data_to_the_file_ {
            get {
                return ResourceManager.GetString("MainForm_SaveXmlAsToolStripMenuItemClick_Error_during_saving_XML_file_with_data_t" +
                        "o_the_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form contains error(s)!.
        /// </summary>
        internal static string MainForm_SaveXmlAsToolStripMenuItemClick_Form_contain_error_ {
            get {
                return ResourceManager.GetString("MainForm_SaveXmlAsToolStripMenuItemClick_Form_contain_error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file as....
        /// </summary>
        internal static string MainForm_SaveXmlAsToolStripMenuItemClick_Save_file_as___ {
            get {
                return ResourceManager.GetString("MainForm_SaveXmlAsToolStripMenuItemClick_Save_file_as___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string MainForm_SaveXmlAsToolStripMenuItemClick_XML_files____xml____xml_All_files__________ {
            get {
                return ResourceManager.GetString("MainForm_SaveXmlAsToolStripMenuItemClick_XML_files____xml____xml_All_files_______" +
                        "___", resourceCulture);
            }
        }
    }
}
